sprint_3
DmitriyExcl/middle.messenger.praktikum.yandex pull request #3
Opened 2022-07-31 18:12 UTC by DmitriyExcl

Роутинг + пробный тест и база для WS

Роутинг страдает, разбираюсь с этим, + нужно сделать нормальную верстку, с этим все печально, настроил пока тесты и написал базу для сокетов

2022-08-01 08:34 UTC, ivan-infro commented
Команды линтеров должны отрабатывать без ошибок

ESLint: ✖ 487 problems (471 errors, 16 warnings)
stylelint: Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?

2022-08-01 08:40 UTC, ivan-infro commented
Чтобы работал роутинг в appServer.js, необходимо добавить обработчик на все пути (`app.use('*', () => {})`) и возвращать по ним index.html

2022-08-01 08:49 UTC, ivan-infro requested changes

2022-08-01 08:49 UTC, ivan-infro commented on src/mainRouting.ts
> +// import { renderDOM, registerComponent, Store, BrowserRouter } from 'core';
Не храните закомментированный и неиспользуемый код в репозитории, это затрудняет чтение

2022-08-01 08:49 UTC, ivan-infro commented on src/mainRouting.ts
> +import * as components from './components';
Обратите внимание, что папка Components у вас названа с большой буквы, а в импорте - с маленькой. Из-за этого не работает сборка в регистрозависимой файловой системе (например, в большинстве дистрибитувах Linux, настроенных по умолчанию). Необходимо либо поправить импорт, либо переименовать папку. Чтобы закоммитить переименование папки, нужно будет сделать 2 коммита: удаление, затем коммит этой же папки, но с новым именем

2022-08-01 08:49 UTC, ivan-infro commented on package.json
> +    "sass": "^1.49.9",
В рамках текущего проекта это не особо важно, но хорошей практикой является добавление зависимостей сборки в раздел devDependencies, а в разделе dependencies только runtime зависимости

2022-08-01 08:49 UTC, ivan-infro commented on src/index.html
> +      <a href="registration">registration</a>
Форма регистрации не работает (обновляется страница, данные сбрасываются)

2022-08-01 08:49 UTC, ivan-infro commented on src/Utils/merge.test.ts
> +  expect(mergeDeep({ a: 1 }, { b: 2 })).toStrictEqual({ a: 1, b: 2 });
В зависимостях отсутствует jest, отсутствует команда запуска тестов

2022-08-13 14:13 UTC, DmitriyExcl commented
Много всего переделал, во первых переделал половину проекта, компоненты страницы и другое. Добавил нормальный роутинг + реализовал полное взаимодействие чатов с WS плюс по заданию. Убрал некоторые страницы и сделал их как модальные окна, есть еще что дорабатывать, но по заданию(ТЗ) вроде все готово, в рамках доработок буду еще катить правки по верстке, потому как сейчас добавил глобальные цвета но есть, еще с чем поработать, главное основной функционал переработал и сделал все более корректным образом + добавил некоторые правила для линта и написал один тес( это тоже буду дорабатывать)

2022-08-13 14:14 UTC, DmitriyExcl commented on package.json
> +    "sass": "^1.49.9",
Да, на дальнейшее учту этот момент, вроде про это знаю, но все равно качу пакеты в dep раздел)))

2022-08-13 14:14 UTC, DmitriyExcl commented on src/mainRouting.ts
> +import * as components from './components';
Спасибо за это замечания, впредь все переделал под нижний регистр

2022-08-13 14:14 UTC, DmitriyExcl commented on src/mainRouting.ts
> +// import { renderDOM, registerComponent, Store, BrowserRouter } from 'core';
Иногда проскальзывает

2022-08-15 11:16 UTC, ivan-infro commented
Дмитрий, добрый день!

Не удалось запустить тест, команда yarn test (npm run test) выдает ошибку отсутствующего jest (его действительно нет в package.json)
`/bin/sh: 1: jest: not found`

2022-08-15 11:17 UTC, ivan-infro commented
eslint не должен возвращать ошибок (сейчас: ✖ 108 problems (64 errors, 44 warnings))

2022-08-15 11:20 UTC, ivan-infro commented
Не выполнено условие:

> При обновлении страницы с определённым URL должна отображаться та же самая страница. То есть если пользователь зашел, например, на страницу регистрации и обновил её, она загрузится снова.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/5419627/184626336-0026ab2e-3933-436e-84f7-6ead8c2bc63b.png">

2022-08-15 11:23 UTC, ivan-infro commented
Ссылки на этой странице не рабочие
<img width="838" alt="image" src="https://user-images.githubusercontent.com/5419627/184626749-6168e7af-85cb-4811-89da-d940842390ce.png">

2022-08-15 11:27 UTC, ivan-infro commented
Добавление пользователя в чат работает, но интерфейс выглядит сломанным. Не подгрузились стили?
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/5419627/184627252-3e98a892-08b6-4b2b-9577-99981c06e8e8.png">

2022-08-16 19:48 UTC, DmitriyExcl commented
> Не выполнено условие:
> 
> > При обновлении страницы с определённым URL должна отображаться та же самая страница. То есть если пользователь зашел, например, на страницу регистрации и обновил её, она загрузится снова.
> 
> <img alt="image" width="560" src="https://user-images.githubusercontent.com/5419627/184626336-0026ab2e-3933-436e-84f7-6ead8c2bc63b.png">

Я могу видео отправить, скрины скинуть, я на локалке не могу добиться такого поведения, при нажатии кнопки перезагрузки ( в самом браузере) форма остается на месте, возвращаюсь на эту же форму

2022-08-16 19:51 UTC, DmitriyExcl commented
> Ссылки на этой странице не рабочие <img alt="image" width="838" src="https://user-images.githubusercontent.com/5419627/184626749-6168e7af-85cb-4811-89da-d940842390ce.png">

Как они не рабочие? Ну реально странно, я полное видео могу записать, могу на встрече показать как эти ссылки работают, создание чата и переход в профиль, все работает и переходит, как я могу это показать? Я может не про те ссылки имею ввиду ?

2022-08-16 19:52 UTC, DmitriyExcl commented
> Добавление пользователя в чат работает, но интерфейс выглядит сломанным. Не подгрузились стили? <img alt="image" width="1356" src="https://user-images.githubusercontent.com/5419627/184627252-3e98a892-08b6-4b2b-9577-99981c06e8e8.png">

Да, тут стили не доделал

2022-08-17 13:53 UTC, ivan-infro commented
Действую по шагам, описанным в README, но тесты не запускаются.
Обратите внимание, что nodejs может использовать глобально установленные пакеты (`npm i -g / yarn global add`), но такие пакеты не переносятся с репозиторием. Вам необходимо указать все используемые пакеты в package.json

Команды, перечисленные в README для запуска,
`yarn`
`yarn start`
не вызывают Parcel, папка dist не создается и сервер возвращает ошибку Not found.

В appServer.js есть только один вызов app.use:
`app.use(express.static(__dirname + "/dist"));` 
В таком виде сервер не отдает ничего, кроме статичных файлов (в т.ч. index.html по корневому пути). Поэтому обновление страницы http://localhost:3000/sign-in возвращает Cannot GET /sign-in.

Если у вас локально все работает, то рекомендую проверить дополнительно:
- что все изменения добавлены и запушены в git
- локально тестируете из чистого состояния, нету влияения предыдущих сборок (удалить папки dist, cache)
- проверяете на том же порту, что и описан в readme (localhost:3000)

2022-08-17 14:00 UTC, DmitriyExcl commented
> Действую по шагам, описанным в README, но тесты не запускаются. Обратите внимание, что nodejs может использовать глобально установленные пакеты (`npm i -g / yarn global add`), но такие пакеты не переносятся с репозиторием. Вам необходимо указать все используемые пакеты в package.json
> 
> Команды, перечисленные в README для запуска, `yarn` `yarn start` не вызывают Parcel, папка dist не создается и сервер возвращает ошибку Not found.
> 
> В appServer.js есть только один вызов app.use: `app.use(express.static(__dirname + "/dist"));` В таком виде сервер не отдает ничего, кроме статичных файлов (в т.ч. index.html по корневому пути). Поэтому обновление страницы http://localhost:3000/sign-in возвращает Cannot GET /sign-in.
> 
> Если у вас локально все работает, то рекомендую проверить дополнительно:
> 
> * что все изменения добавлены и запушены в git
> * локально тестируете из чистого состояния, нету влияения предыдущих сборок (удалить папки dist, cache)
> * проверяете на том же порту, что и описан в readme (localhost:3000)
> * используйте для проверки разные браузеры

Да, это мой косяк, не правильно указал запуск, запуск парсела и всего остального описаны в Package.json

2022-08-17 14:03 UTC, ivan-infro commented
Версия на Netlify тоже нерабочая:
<img width="1369" alt="Screenshot 2022-08-17 at 17 03 02" src="https://user-images.githubusercontent.com/5419627/185154263-8d1848e7-cc43-4e12-b6af-934c8d565b70.png">

2022-08-17 14:19 UTC, ivan-infro requested changes

2022-08-17 14:19 UTC, ivan-infro commented on src/app/utils/last.ts
> +export default function last<T = string>(arr: T[]): T {
В текущей реализации может вернуться undefined (если массив пустой), но описание типа этого не подразумевает. Необходимо либо добавить проверку длины массива и выбрасывать исключение, либо добавить в возвращаемый тип undefined

2022-08-17 14:19 UTC, ivan-infro commented on src/app/services/web-socket/web-socket.ts
> +      `wss://ya-praktikum.tech/ws/chats/${store.getState().user!.id}/${currentChatId}/${token}`,
Выносите константы в отдельные файлы

2022-08-17 14:19 UTC, ivan-infro commented on src/app/services/web-socket/web-socket.ts
> +          (document.querySelector('#message') as HTMLElement)?.focus();
document.querySelector('#message') можно вынести в отдельную переменную чтобы не совершать поиск по DOM каждый раз

2022-08-17 14:19 UTC, ivan-infro commented on src/app/services/web-socket/web-socket.ts
> +        if (Array.isArray(JSON.parse(event.data))) {
JSON.parse необходимо оборачивать в try catch, т.к. от сервера могут придти поломанные данные

2022-08-17 14:19 UTC, ivan-infro commented on src/app/services/constants.ts
> +export const REG_EXP_VALIDATE_EMAIL = /^[\w\.-]+@[A-Za-z]+\.[A-Za-z]+$/;
`mail@awesome-company.games` валидный email, который не пройдет проверку данным регулярным выражением

2022-08-17 14:19 UTC, ivan-infro commented on src/app/services/chats/chats.service.ts
> +      this.getChatUsers(+last(document.location.pathname.split('/')));
Здесь chats.service.ts обращается напрямую к document.location
Почему это плохо? Есть несколько причин:
- неявная связанность логики роутинга и сервиса чатов (нельзя поменять формат урла, не сломав данный сервис)
- обращение к глобальным браузерным переменным
- нету проверки, что оператор "+" вернул не NaN

2022-08-22 19:58 UTC, DmitriyExcl commented on src/app/services/web-socket/web-socket.ts
> +          (document.querySelector('#message') as HTMLElement)?.focus();
Это критично?

2022-08-22 19:59 UTC, DmitriyExcl commented on src/app/services/web-socket/web-socket.ts
> +      `wss://ya-praktikum.tech/ws/chats/${store.getState().user!.id}/${currentChatId}/${token}`,
Хорошо, спасибо за замечание учту это

2022-08-22 20:03 UTC, DmitriyExcl commented
<img width="1159" alt="Снимок экрана 2022-08-22 в 23 02 37" src="https://user-images.githubusercontent.com/101922359/186008730-2e647bee-e022-4e4c-a41e-2117d4f096f4.png">
скрин прогона теста

2022-08-22 20:05 UTC, DmitriyExcl commented on src/app/services/constants.ts
> +export const REG_EXP_VALIDATE_EMAIL = /^[\w\.-]+@[A-Za-z]+\.[A-Za-z]+$/;
Поправил

2022-08-22 20:05 UTC, DmitriyExcl commented on src/app/services/chats/chats.service.ts
> +      this.getChatUsers(+last(document.location.pathname.split('/')));
Учту этот момент

2022-08-22 20:07 UTC, DmitriyExcl commented on src/app/utils/last.ts
> +export default function last<T = string>(arr: T[]): T {
Поправил

2022-08-24 18:00 UTC, merged